### ISSUE TITLE
Please use stronger cipher by default

### ISSUE THREAD

**Issue by bigon** [vStone/puppet-apache#25]
Hi,

By default, the module is using LOW ciphers (the default in CentOS). I would suggest to use stronger one.

Debian is using by default in wheezy:

```
HIGH:MEDIUM:!aNULL:!MD5
```

We could also use something like:

```
SSLHonorCipherOrder On
SSLCipherSuite ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:RC4:HIGH:!MD5:!aNULL:!EDH
```

to also mitigate the BEAST attack. This would require to add a parameter for SSLHonorCipherOrder (default to off)

**Comment by vStone** [comment]
Please test the latest development branch to see if this works for you. I will create a new release after confirmation ;)

**Comment by vStone** [comment]
Closing due to no reply. If this is not fixed enough, reopen.

**Comment by bigon** [comment]
Oh sorry, yes seems to fix as expected, thanks
