### ISSUE TITLE
05_mod.conf: No matches for the wildcard '*.conf' in '/etc/apache2/conf.d/mod.d'

### ISSUE THREAD

**Issue by carroarmato0** [vStone/puppet-apache#32]
On a fresh installation of Ubuntu 13.10 (and likely Debian based systems in general):

  class{'apache::params':}
  class {'apache':}

  apache::vhost {'somehost.org':}

---

Output of config test was:
apache2: Syntax error on line 221 of /etc/apache2/apache2.conf: Syntax error on line 13 of /etc/apache2/conf.d/05_mod.conf: No matches for the wildcard '*.conf' in '/etc/apache2/conf.d/mod.d', failing (use IncludeOptional if required)
Action 'configtest' failed.
The Apache error log may have more information.

---
### File managed with puppet
# Served by:        'puppet.lxc'
# Module:           'apache'
# Template source:  'MODULES/apache/templates/confd/confd_include.erb'
### Parameters:
# confd:            'mod.d'
# order:            '05'
# purge:            'false'
# use_config_root:  'false'
### 
# Includes:

Include conf.d/mod.d/*.conf

**Comment by vStone** [comment]
This is due to apache 2.4. For now, I'm gonna close this until I have time to start with a apache 2.4 compliant version of the module.
